export const LOGIN_DETAILS = "LOGIN_DETAILS";
export const REGISTER_DETAILS = "REGISTER_DETAILS";

//FILE UPLOAD
export const GET_FILE_DETAILS = "GET_FILE_DETAILS";
export const GET_FILE_DETAILS_SUCCESS = "GET_FILE_DETAILS_SUCCESS";
export const GET_FILE_DETAILS_FAILURE = "GET_FILE_DETAILS_FAILURE";
export const ADD_FILE_DATA = "ADD_FILE_DATA";
export const FILTER_FILE_DATA = "FILTER_FILE_DATA";